### ISSUE TITLE
TypeError: Invalid Version: v1.0

### ISSUE THREAD

**Issue by surfer190** [ServerCentral/praeco#164]
I've upgraded the images and reup'ed the containers:

```
REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE
servercentral/praeco       latest              d469a8b9b20d        8 hours ago         1.36GB
servercentral/elastalert   latest              ce3c9ff6adb8        4 weeks ago         459MB
```

However when I log in I still have `praeco 0.4.5` the top right and error `Internal error - TypeError: Invalid Version: v1.0`

**Comment by johnsusek** [comment]
Oops I put a "v" in from of 1.0 in github, which broke the update checks. I just fixed that, can you try it again?

**Comment by surfer190** [comment]
Hmmm, same error but without the `v`: `TypeError: Invalid Version: 1.0`

<img width="610" alt="Screen Shot 2019-09-30 at 07 43 47" src="https://user-images.githubusercontent.com/3285222/65852397-4bce1380-e356-11e9-8278-e4765d2e23a7.png">

Also the version still shows as `0.45`:

<img width="252" alt="Screen Shot 2019-09-30 at 07 43 57" src="https://user-images.githubusercontent.com/3285222/65852408-54264e80-e356-11e9-9880-ed418f137b9a.png">

**Comment by johnsusek** [comment]
*facepalm* this was because I used 1.0 not 1.0.0. Thx
